//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `Player.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Demo;

public interface Subject extends com.zeroc.Ice.Object
{
    void attach(String userId, ObserverPrx obs, com.zeroc.Ice.Current current);

    void sendAudio(String fromUser, byte[] data, com.zeroc.Ice.Current current);

    void sendAudioMessage(String fromUser, String toUser, byte[] data, com.zeroc.Ice.Current current);

    String[] getConnectedUsers(com.zeroc.Ice.Current current);

    void startCall(String fromUser, String toUser, com.zeroc.Ice.Current current);

    void acceptCall(String fromUser, String toUser, com.zeroc.Ice.Current current);

    void rejectCall(String fromUser, String toUser, com.zeroc.Ice.Current current);

    void colgar(String fromUser, String toUser, com.zeroc.Ice.Current current);

    /** @hidden */
    static final String[] _iceIds =
    {
        "::Demo::Subject",
        "::Ice::Object"
    };

    @Override
    default String[] ice_ids(com.zeroc.Ice.Current current)
    {
        return _iceIds;
    }

    @Override
    default String ice_id(com.zeroc.Ice.Current current)
    {
        return ice_staticId();
    }

    static String ice_staticId()
    {
        return "::Demo::Subject";
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_attach(Subject obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_userId;
        ObserverPrx iceP_obs;
        iceP_userId = istr.readString();
        iceP_obs = ObserverPrx.uncheckedCast(istr.readProxy());
        inS.endReadParams();
        obj.attach(iceP_userId, iceP_obs, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_sendAudio(Subject obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_fromUser;
        byte[] iceP_data;
        iceP_fromUser = istr.readString();
        iceP_data = istr.readByteSeq();
        inS.endReadParams();
        obj.sendAudio(iceP_fromUser, iceP_data, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_sendAudioMessage(Subject obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_fromUser;
        String iceP_toUser;
        byte[] iceP_data;
        iceP_fromUser = istr.readString();
        iceP_toUser = istr.readString();
        iceP_data = istr.readByteSeq();
        inS.endReadParams();
        obj.sendAudioMessage(iceP_fromUser, iceP_toUser, iceP_data, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_getConnectedUsers(Subject obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        inS.readEmptyParams();
        String[] ret = obj.getConnectedUsers(current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        ostr.writeStringSeq(ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_startCall(Subject obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_fromUser;
        String iceP_toUser;
        iceP_fromUser = istr.readString();
        iceP_toUser = istr.readString();
        inS.endReadParams();
        obj.startCall(iceP_fromUser, iceP_toUser, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_acceptCall(Subject obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_fromUser;
        String iceP_toUser;
        iceP_fromUser = istr.readString();
        iceP_toUser = istr.readString();
        inS.endReadParams();
        obj.acceptCall(iceP_fromUser, iceP_toUser, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_rejectCall(Subject obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_fromUser;
        String iceP_toUser;
        iceP_fromUser = istr.readString();
        iceP_toUser = istr.readString();
        inS.endReadParams();
        obj.rejectCall(iceP_fromUser, iceP_toUser, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_colgar(Subject obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_fromUser;
        String iceP_toUser;
        iceP_fromUser = istr.readString();
        iceP_toUser = istr.readString();
        inS.endReadParams();
        obj.colgar(iceP_fromUser, iceP_toUser, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /** @hidden */
    final static String[] _iceOps =
    {
        "acceptCall",
        "attach",
        "colgar",
        "getConnectedUsers",
        "ice_id",
        "ice_ids",
        "ice_isA",
        "ice_ping",
        "rejectCall",
        "sendAudio",
        "sendAudioMessage",
        "startCall"
    };

    /** @hidden */
    @Override
    default java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceDispatch(com.zeroc.IceInternal.Incoming in, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        int pos = java.util.Arrays.binarySearch(_iceOps, current.operation);
        if(pos < 0)
        {
            throw new com.zeroc.Ice.OperationNotExistException(current.id, current.facet, current.operation);
        }

        switch(pos)
        {
            case 0:
            {
                return _iceD_acceptCall(this, in, current);
            }
            case 1:
            {
                return _iceD_attach(this, in, current);
            }
            case 2:
            {
                return _iceD_colgar(this, in, current);
            }
            case 3:
            {
                return _iceD_getConnectedUsers(this, in, current);
            }
            case 4:
            {
                return com.zeroc.Ice.Object._iceD_ice_id(this, in, current);
            }
            case 5:
            {
                return com.zeroc.Ice.Object._iceD_ice_ids(this, in, current);
            }
            case 6:
            {
                return com.zeroc.Ice.Object._iceD_ice_isA(this, in, current);
            }
            case 7:
            {
                return com.zeroc.Ice.Object._iceD_ice_ping(this, in, current);
            }
            case 8:
            {
                return _iceD_rejectCall(this, in, current);
            }
            case 9:
            {
                return _iceD_sendAudio(this, in, current);
            }
            case 10:
            {
                return _iceD_sendAudioMessage(this, in, current);
            }
            case 11:
            {
                return _iceD_startCall(this, in, current);
            }
        }

        assert(false);
        throw new com.zeroc.Ice.OperationNotExistException(current.id, current.facet, current.operation);
    }
}
